### ISSUE TITLE
Passing all command-line arguments to Property Object

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/yarp-devices#33] opened 2016-02-08 10:41 UTC
When extracting a group from a Resource Finder, only arguments coming from the config file are passed to the Property Object. Command-line arguments are ignored, and this may cause problems in the future.

Possible solutions:
- Append command line arguments to group arguments coming from the file as a new group in the Property Object
- Add support in YARP for extracting parameters depending on the origin of them (either command-line or file)

**Comment by PeterBowman** [comment] 2018-10-07 12:20
For instance, let's take [oneCanBusOneWrapper.ini](https://github.com/roboticslab-uc3m/yarp-devices/blob/ab74640ab5d97b4054bd74d6f12aa35e0f5af740/share/oneCanBusOneWrapper/conf/oneCanBusOneWrapper.ini). The `name` property to the `[wrapper0]` group is set to `/wrapper0` in the .ini file. I'd expect that the following command would override the default value and pick `/myPort` instead (given also a default context and .ini config file, therefore no `--context` nor `--from` are shown here):

```shell
$ oneCanBusOneWrapper --wrapper0::name /myPort
```

The custom port is correctly parsed by `yarp::dev::ResourceFinder`, but dismissed during the initialization by [`yarp::os::Property::fromString()`](http://www.yarp.it/classyarp_1_1os_1_1Property.html#a0b938dbb6cf9e92a845cb18509865c62).

**Edit:** tested on YARP 2.3.70.2.

**Comment by PeterBowman** [comment] 2018-10-07 13:00
Relevant lines upstream: [ResourceFinder.cpp](https://github.com/robotology/yarp/blob/0e67a89e8c147d6fc9547a937ca45768f1ca52d7/src/libYARP_OS/src/ResourceFinder.cpp#L188-L207). I'd deem that placing the call to [`yarp::os::Property::fromConfigFile()`](http://www.yarp.it/classyarp_1_1os_1_1Property.html#a275d87fffe69cd2333b777b721967ab3) last would give precedence to command-line user arguments over `--from`.

**Comment by PeterBowman** [comment] 2018-10-07 16:00
> Add support in YARP for extracting parameters depending on the origin of them (either command-line or file)

Compare:

* [`yarp::os::Property::fromArguments`](http://www.yarp.it/classyarp_1_1os_1_1Property.html#abfd96557e2cebc3473e297afbdcf412e)
* [`yarp::os::Property::fromConfigFile`](http://www.yarp.it/classyarp_1_1os_1_1Property.html#a275d87fffe69cd2333b777b721967ab3)

...and others.

**Comment by PeterBowman** [comment] 2018-10-07 16:24
Looks like the `ResourceFinder` mechanism works as intended, i.e. it correctly merges both command-line and config file properties and gives more precedence to the former (via `find`). However, we need to use `Property::fromString` [here](https://github.com/roboticslab-uc3m/yarp-devices/blob/ab74640ab5d97b4054bd74d6f12aa35e0f5af740/libraries/OneCanBusOneWrapper/OneCanBusOneWrapper.cpp#L74) which, in turn, picks the latter. Compare docs for [`fromConfigFile`](http://www.yarp.it/classyarp_1_1os_1_1Property.html#a275d87fffe69cd2333b777b721967ab3) and [`fromString`](http://www.yarp.it/classyarp_1_1os_1_1Property.html#a0b938dbb6cf9e92a845cb18509865c62).

**Comment by PeterBowman** [comment] 2018-10-08 17:53
Reported upstream at https://github.com/robotology/yarp/issues/1889.

**Comment by PeterBowman** [comment] 2019-12-30 17:32
> Reported upstream at [robotology/yarp#1889](https://github.com/robotology/yarp/issues/1889).

The former *launchManipulation* app has been improved and renamed to *launchCanBus* in https://github.com/roboticslab-uc3m/yarp-devices/issues/20. Also, the .ini parse system has been fully revamped (https://github.com/roboticslab-uc3m/yarp-devices/issues/237) and there is currently no urgent need to accept additional command line arguments in our CAN-based tools. Therefore, I'm marking this as invalid and superseded by the upstream issue.

**Closed as not planned by PeterBowman** 2019-12-30 17:32 UTC
Labels: invalid, documentation, priority: low, program: launchCanBus

**Comment by PeterBowman** [comment] 2019-12-30 17:33
> Add support in YARP for extracting parameters depending on the origin of them (either command-line or file)

See [`yarp::os::ResourceFinderOptions`](http://www.yarp.it/classyarp_1_1os_1_1ResourceFinderOptions.html) and related methods at [`yarp::os::ResourceFinder`](http://www.yarp.it/classyarp_1_1os_1_1ResourceFinder.html).
