### ISSUE TITLE
Needs some kebab-case

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#107] opened 2017-03-19 21:22 UTC
Too much snake_case. ;-)

**Comment by PeterBowman** [comment] 2017-11-29 11:36
Kebab was served hot by @rsantos88 at #142. Marking as duplicate of #135, though, and closing.

**Closed as duplicate by PeterBowman** 2017-11-29 11:36 UTC
Labels: duplicate, priority: low

**Comment by jgvictores** [comment] 2017-11-29 17:36
> Kebab was served hot by @rsantos88 at #142. Marking as duplicate of #135, though, and closing.

@PeterBowman Best comment con kebab-case ever LOL
